### ISSUE TITLE
Try it in your browser doesn't work

### ISSUE THREAD

**Issue by PatSte87** [malb/lattice-estimator#108]
I wanted to try it my browser but I got the following error message:

Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2docker_kx6m_0j'...
HEAD is now at d1b7d11 Update jupyter-notebooks to output generated at 7ea215a
Using DockerBuildPack builder
Step 1/5 : FROM sagemathinc/cocalc:latest
pull access denied for sagemathinc/cocalc, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by malb** [comment]
Ah dang, will need to see if there's another docker image we can use easily

**Comment by malb** [comment]
fixed.
