### ISSUE TITLE
Hacky approach to getting multiple short vectors

### ISSUE THREAD

**Issue by malb** [malb/lattice-estimator#12]
@blowfish880 wrote:
> But this points to the larger issue that the current way these different approaches of obtaining many short vectors from the reduction cost models are handled is somewhat hacky in the dual attack. Ideally, one would be able to request a certain number of short vectors from the model and the model would return the cost of obtaining all of them and what length they would have. Maybe the cleanest way would be to have cost models not being just functions, but objects with two methods: 1) something like reduce_basis(beta) that returns the cost of a reduction + the shape, and 2) something like short_vectors(beta, N) that returns the cost of obtaining N short vectors and their length. This would reflect the two different ways that BKZ is used in the different attacks: obtaining nice bases and as an approximate SVP oracle. But if the dual attack is the only place that comes up, not sure if it's worth it.

**Comment by malb** [comment]
In principle, I like the approach of turning the cost models into objects with specialised functions/methods that fall back to the generic solution. 

However, I guess `short_vectors(beta, N)` should also accept and/or return `slack` which would be `\sqrt{4/3}` for the sieves etc. 

Then there's dimensions for free to take into account.

So maybe this gets quite specific and should be its own little module?

**Comment by blowfish880** [comment]
So you mean something like a approx_svp module that relies on the reduction module? But that would seem like we are just shifting the problem: this module would still need to figure out if we are dealing with a full sieve or a d4f sieve or an enumeration, which is again hacky if the reduction doesn't give you that info.

**Comment by malb** [comment]
Thinking about it, I guess the key problem is the API. Do we put in `beta` and get out `N, f, c` where `N` is a number of vectors, `f` is a growth factor and `c` is a cost? If we make any of those an input the caller needs to know about the underlying algorithms. With that API I can see how to roll it into the `reduction.py` stuff.

**Comment by blowfish880** [comment]
I agree with `f` and `c`, not sure if I agree with `N` being an output. For example, if the caller wants only one vector, then `f=1` for any algorithm, including sieving. It's only when the caller wants many vectors that we have `f > 1`. But maybe I'm overthinking this and it is reasonable to assume that the caller wants as many vectors as possible when calling the model.

**Comment by malb** [comment]
Okay, I think then `N` should be both an input and an output. if `N=None` then the algorithm picks. If `N is not None` then the algorithm will output at least `N` vectors. So for  sieve if `N=1024` the algorithm will still output `2^0.21b` vectors etc.

I'm getting an idea of how it fits together, let me see what I can do (next-ish week or so). If you're trigger happy, feel free to go ahead in the meantime though :)

**Comment by malb** [comment]
How about this: https://github.com/malb/lattice-estimator/tree/reduction-objects ?

**Comment by blowfish880** [comment]
This looks very nice. I think the dual code will be much cleaner this way and it'll be straight-forward to incorporate new ways of generating vectors, e.g. the two step approach from the AC21 paper. 

A couple of comments/questions though: 
1) the three methods of `ReductionCost` producing the short vectors (`short_vectors`, `short_vectors_simple`, `_short_vectors_sieve`) all state in the comments that it is assumed that the basis is already BKZ reduced. This is only really true for `short_vectors` as far as i can tell, the other two give the correct estimate even for non-reduced bases. So maybe it'd make sense to make this consistent by removing this assumption all together and add the cost of reduction in `short_vectors`?

2) I don't quite follow the `Kyber.short_vectors` method. I'm assuming the call
```
return self._short_vectors_sieve(floor(self.d4f(beta)), d, N)
```
should actually be 
```
return self._short_vectors_sieve(beta - floor(self.d4f(beta)), d, N)
```
So is the idea that even using d4f you get many short vectors, just not as many? So it is assumed that in the last tour the head of the basis is sieved as well? (I was under the impression that the head of the basis is only ever in the lifting context, never actually in the sieving context, but I might be wrong and it would make sense to actually sieve there as well towards the end but with a smaller block size.)

**Comment by malb** [comment]
On 1: 
- You're right. I was assuming we'd need BKZ-beta in there to get delta^d but we only express length relative to the shortest vector of the block.
- I think it should be `short_vectors_simple` not `short_vectors` though, i.e. `short_vectors` calls the SVP oracle. 
- I made in mistake in Kyber: `sqrt{4/3}` is wrt to the sieving dimension but should be wrt to the SVP dimension.

On 2:
- This is essentially one of the AC21 "tricks", just sieve again in some smaller dimension to get many vectors out.
- Yet, that's a bug and should be `beta - d4f(beta)`

**Comment by malb** [comment]
Oh, I forgot: I don't think we should roll the preprocessing into this function. You need to consider it anyway to get the expected length of the shortest vector and I'm thinking of algorithms that somewhat adaptively ask for more short vectors for some reason.

**Comment by blowfish880** [comment]
Let's say I want to know the cost of computing N short vectors from an unreduced basis (the typical scenario in the dual attack). How do I do that then? If I use a cost model that uses `ReductionCost.short_vectors`, I need to first call the model to estimate the running time of the preprocessing and then call `short_vectors` and then add them. If I use any other model, I need to call `short_vectors` right away (or I'll overestimate the running time by potentially a factor 2). So this would require the calling function to know the cost model, something which I was hoping to avoid, since it seems hacky. (I.e. there needs to be some if-else again.)

**Comment by malb** [comment]
Okay, let me add the preprocessing cost (but it can be disabled with a parameter)

**Comment by malb** [comment]
> On 1:
>     * I made in mistake in Kyber: `sqrt{4/3}` is wrt to the sieving dimension but should be wrt to the SVP dimension.

Just in case someone is reading this later, that's not right.

**Comment by malb** [comment]
Alright, updated.

**Comment by blowfish880** [comment]
This looks really nice. I would approve a PR.

**Comment by malb** [comment]
Cool, shall I PR it and you test it by updating the dual attack code?

**Comment by blowfish880** [comment]
Yeah, go ahead. (I'm actually already adapting the dual attack.)

**Comment by blowfish880** [comment]
Ok, I think I got the dual attack updated and it seems to work, but there are a couple of tests that are failing by throwing an exception and I cannot figure out why. Not sure if this is the right place to discuss this, so if not, we can take it somewhere else. But this is the issue:
```
sage: LWE.estimate.rough(Kyber512)
...
... lattice-estimator/estimator/lwe_dual.py in cost(solver, params, beta, zeta, h1, success_probability, red_cost_model, use_lll, log_level)
    138 
    139         # only care about the scaling factor and don't know d yet -> use beta as dummy d
--> 140         rho, _, _ = red_cost_model.short_vectors(beta=beta, d=beta)
    141 
    142         params_slv, m_ = DualHybrid.dual_reduce(

TypeError: _short_vectors_sieve() missing 1 required positional argument: 'self'
```

However, as far as I can tell, `estimate.rough` should simply be making this call:
```
sage: lwe.dual_hybrid(Kyber512, red_cost_model=RC.ADPS16, mitm_optimization=False)
rop: ≈2^121.9, mem: ≈2^116.8, m: 512, β: 417, d: 1013, ↻: 1, ζ: 11, tag: dual_hybrid
```
which goes through without a problem. I've tried printing the input to `DualHybrid.__call__` and they look identical in both cases. But there must be something about how `batch_estimate` is calling `dual_hybrid`. Any ideas?

**Comment by blowfish880** [comment]
Bug fixes magically happening in my branch? Of course that's ok :)
