### ISSUE TITLE
Primal Hybrid gone wrong?

### ISSUE THREAD

**Issue by malb** [malb/lattice-estimator#20]
``` python
sage: D = ND.SparseTernary(1024, 256 // 2)
sage: LAC192v3a = LWE.Parameters(n=1024, q=251, Xs=D, Xe=D, m=1024, tag="LAC-192-v3a")
sage: LWE.primal_hybrid(LAC192v3a)
rop: ≈2^360.9, red: ≈2^359.9, svp: ≈2^359.9, β: 866, η: 2, ζ: 576, |S|: ≈2^510.8, d: 1003, prob: ≈2^-82.3, ↻: ≈2^84.5, tag: hybrid

sage: LWE.primal_hybrid(LAC192v3a, red_shape_model="CN11")
rop: ≈2^405.0, red: ≈2^405.0, svp: ≈2^378.1, β: 40, η: 2, ζ: 0, |S|: 1, d: 665, prob: ≈2^-357.2, ↻: ≈2^359.4, tag: hybrid
```

This doesn't look right.

**Comment by malb** [comment]
It seems to boil down to `mitm_babai_probability` which perhaps doesn't like the tail shape (?) In that case, we should preprocess with Dual-BKZ to get a nice line in the critical lifting part?

**Comment by blowfish880** [comment]
I personally believe that for decoding one should always reduce the dual basis. Then the GSA should be quite accurate in the tails and the result of using the simulator and the GSA should be fairly close, I would expect.

**Comment by bencrts** [comment]
I've started to investigate this, will report back and open a PR asap.

**Comment by bencrts** [comment]
I've made a first attempt to go via the dual basis on pull request #29. As the PR stands, this is the output for the same parameters as above:

```python
sage: from estimator import *
sage: sage: from estimator import *
sage: D = ND.SparseTernary(1024, 256 // 2)
sage: sage: LAC192v3a = LWE.Parameters(n=1024, q=251, Xs=D, Xe=D, m=1024, tag="LAC-192-v3a")

sage: sage: LWE.primal_hybrid(LAC192v3a)
rop: ≈2^361.7, red: ≈2^360.7, svp: ≈2^360.7, β: 863, η: 2, ζ: 576, |S|: ≈2^513.9, d: 1001, prob: ≈2^-81.6, ↻: ≈2^83.8, tag: hybrid

sage: sage: LWE.primal_hybrid(LAC192v3a, red_shape_model="CN11")
rop: ≈2^369.6, red: ≈2^368.6, svp: ≈2^368.6, β: 877, η: 2, ζ: 591, |S|: ≈2^521.6, d: 995, prob: ≈2^-85.7, ↻: ≈2^87.9, tag: hybrid
```

much closer, and doesn't output the estimate for `β: 40` but I guess we can discuss the specifics on the PR.
