### ISSUE TITLE
Kyber reduction model too optimistic with many short vectors?

### ISSUE THREAD

**Issue by blowfish880** [malb/lattice-estimator#22]
I know I ok'ed the code when it was merged, but looking at it again I think the Kyber model is too optimistic when estimating the cost of producing many short vectors. Specifically, the way it currently works is that `Kyber.short_vectors` calls `ReductionCost._short_vectors_sieve` with `beta-d4f(beta)`, which in turn calls `Kyber.__call__` with that beta. But `Kyber.__call__` will apply `d4f` again before estimating the complexity. So `d4f` is called twice leading to a much smaller `beta` and thus an overly optimistic estimate.

**Comment by malb** [comment]
Ah, good catch. Will fix.

**Comment by blowfish880** [comment]
While you're at it, is it possible that the Kyber estimate for lattice reduction is different from the Kyber documentation? On page 27 of the supporting documentation the final gate count is computed, where the progressive sieving overhead constant C is squared. ([AC:GJ21] do something similar.) In the code, C is only multiplied once into the number of SVP calls. Am I missing something?
