### ISSUE TITLE
Question about stddev of SparseTernary

### ISSUE THREAD

**Issue by 3553x** [malb/lattice-estimator#39]
Hi,
I'm a bit confused by how you calculate the standard deviation for your SparseTernary distribution.
You calculate it as `sqrt( (p + m) / n )`, but doesn't that only apply when the mean is zero? i.e. when `p == m`?
I'd like to use your tool with a binary key and I calculated the standard deviation for a binary key as `sqrt( ( hn - h^2 ) / n^2 )`.
The formula for the general case when `p != m` should also be different.
Am I misunderstanding something or is the code assuming that `p == m`?

**Comment by malb** [comment]
Yeah, that looks like a bug. PR very welcome :)

**Comment by 3553x** [comment]
I wrote a patch and I'm running the tests right now. I'll open a PR once they pass.
