### ISSUE TITLE
"repeat" both a field and a method in Cost

### ISSUE THREAD

**Issue by blowfish880** [malb/lattice-estimator#5]
It looks like having `repeat` be both a method and a field (after calling the method) is not a great idea, since this restricts you to calling `repeat` at most once. This is inconvenient in some cases.

```
sage: from estimator.cost import Cost                                                                                                          
sage: cost = Cost(rop=1)                                                                                                                       
sage: cost.repeat(1).repeat(1)                                                                                                                 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-104-1c5a28bb64f8> in <module>
----> 1 cost.repeat(Integer(1)).repeat(Integer(1))

TypeError: 'sage.rings.integer.Integer' object is not callable
```

**Comment by malb** [comment]
Shall we call the field "repetitions"?

**Comment by blowfish880** [comment]
This would make it very long in the output line compared to the other fields. How about "reps"? Or is that not clear enough?

**Comment by malb** [comment]
`reps` works (but we can also print some unicode symbol in the short form: 𝄆 https://en.wikipedia.org/wiki/Repeat_sign

**Comment by blowfish880** [comment]
I think that might be the cleanest solution. As much as I like the musical solution, I think your latter suggestion is probably the clearest.

**Comment by malb** [comment]
I just tried the latter option in my terminal, and that one didn't work but e.g. ↻ does

**Comment by blowfish880** [comment]
Also good I think.
