### ISSUE TITLE
Example usage Issue & Chat channel

### ISSUE THREAD

**Issue by macknight** [malb/lattice-estimator#67]
Hi,
I see in this example, the code is using n and q, but can I use LogN and LogQ if I don't now exactly n and q?
>>> from estimator import *
>>> schemes.Kyber512
LWEParameters(n=512, q=3329, Xs=D(σ=1.22), Xe=D(σ=1.22), m=512, tag='Kyber 512')
>>> LWE.primal_usvp(schemes.Kyber512)

Another question is except this issue system, any other chat channel in Discord for this project?

BR

**Comment by malb** [comment]
If you only need ballpark figures you can give ballpark inputs, e.g.:

```
LWE.primal_usvp(LWE.Parameters(n=500, q=2^12, Xs=ND.DiscreteGaussian(2.0), Xe=ND.DiscreteGaussian(2.0)))
 rop: ≈2^154.3, red: ≈2^154.3, δ: 1.003702, β: 444, d: 1019, tag: usvp
```

and 

```
LWE.primal_usvp(LWE.Parameters(n=512, q=3989, Xs=ND.DiscreteGaussian(2.0), Xe=ND.DiscreteGaussian(2.0)))
 rop: ≈2^158.3, red: ≈2^158.3, δ: 1.003622, β: 458, d: 1073, tag: usvp
```

We don't have a Discord or so.
