### ISSUE TITLE
Integrating sparseLWE-estimator

### ISSUE THREAD

**Issue by gong-cr** [malb/lattice-estimator#82]
Dear developers,

I was wondering if there is a plan to integrate the sparseLWE estimator from https://github.com/yonghaason/SparseLWE-estimator.  Currently, if I didn't misread the code, the sparse secret distribution in lattice-estimator can only be defined with fixed numbers of +1 and -1.  This is different from SparseLWE-estimator, where one can define the fixed Hamming weight, leading to a potential gap in estimating the security level.
For example:
In lattice-estimator:
```
param = LWE.Parameters(
    n = 16384,
    q = 2**361,
    Xs = ND.SparseTernary(16384, 64, 64),
    Xe = ND.DiscreteGaussian(3.19),
    m = oo
)
LWE.dual_hybrid(param, RC.BDGL16)
```
It returns rop ≈ 2^141.5.

In sparse-LWE estimator:
```
n = 16384; q = next_prime(2^361); alpha = 8/q; h = 128;
print(hybrid_dual(n, alpha, q, secret_distribution=((-1,1),h), reduction_cost_model = BKZ.sieve)) 
```
It returns rop: 2^129.0.

Since SparseLWE-estimator seems to no longer be actively maintained, it would be helpful if lattice-estimator could also be used to analyze sparse secrets with an unfixed number of +1 (or -1).

**Comment by gong-cr** [comment]
Both estimation use BDGL16 (https://github.com/yonghaason/SparseLWE-estimator/blob/25aa7f508863d1a8ca7514836be227a898ccf004/estimator_sparseLWE.py#L1494)

**Comment by bencrts** [comment]
Hi @gong-cr  :-). For sparse secrets I guess using `mitm_optimization = True` is needed to match things up when calling `dual_hybrid()` directly. 

```sage: from estimator import *
sage: param_16384_ternary128_classic_128 = LWE.Parameters(
....:     n = 16384,
....:     q = 2**361,
....:     Xs = ND.SparseTernary(16384, 64, 64),
....:     Xe = ND.DiscreteGaussian(3.19),
....:     m = oo,
....:     tag = "param_16384_ternary128_classic_128"
....: )


sage: LWE.dual_hybrid(param_16384_ternary128_classic_128, mitm_optimization=True, red_cost_model = RC.BDGL16)
rop: ≈2^130.2, mem: ≈2^114.6, m: ≈2^13.6, k: ≈2^11.1, ↻: ≈2^14.2, β: 295, d: 24915, ζ: ≈2^12.0, h1: 21, tag: dual_mitm_hybrid
```
