### ISSUE TITLE
Optimal choice for m in primal attack

### ISSUE THREAD

**Issue by ElenaKirshanova** [malb/lattice-estimator#91]
Hi,
question on the computation of `optimal' m in the primal lattice attack (uSVP) on this line:

https://github.com/malb/lattice-estimator/blob/280496b4828c45d315f23c58dc60fb6203707f24/estimator/lwe_primal.py#L95

As far as I see, the first argument of min{} should be an expression minimizing the right-hand side of the "2016 Estimate" (Eq(2) in https://eprint.iacr.org/2017/815.pdf ). However, when I minimize this RHS, I receive almost the same expression but without the factor 2. In the BDD attack, there is no factor 2 https://github.com/malb/lattice-estimator/blob/280496b4828c45d315f23c58dc60fb6203707f24/estimator/lwe_primal.py#L339 What am I missing here? 

I expect it should not affect the end result for many parameters as the optimal lattice dimension is chosen later.

**Comment by malb** [comment]
I think that's just an oversight. I must have picked some "big enough" `m` to make the optimisation not bomb out. But I agree, it's cleaner to drop the `2`. Can you send a PR?

**Comment by ElenaKirshanova** [comment]
sure, thanks!
